version: '3.8'

services: 
  races:
    build:
      context: ./races
      dockerfile: Dockerfile
    environment:
      PORT: 4001
    ports:
      - 4001:4001

  matches:
    build:
      context: ./matches
      dockerfile: Dockerfile
    environment:
      PORT: 4002
    ports:
      - 4002:4002

networks:
  graphql-cluster:
